name: Livechecks tap mvrpl/unix-apps

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  livecheck-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Livecheck brew linux
        id: brew-linux
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew tap mvrpl/unix-apps https://github.com/mvrpl/unix-apps &&
          brew install jq &&
          brew livecheck --tap mvrpl/unix-apps --json | jq '.[] | select(.version.outdated) | "brew bump-formula-pr \(.formula) --version=\(.version.latest) --no-fork"' | xargs -n1 bash -c '$1;exit 0' bash &&
          git branch linux main && git checkout linux &&
          mv $(brew --repository mvrpl/unix-apps)/*.rb . &&
          git add . && git commit -a -m "linux updates" &&
          git push origin linux
  livecheck-mac-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Livecheck brew mac-arm
        id: brew-mac-arm
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew tap mvrpl/unix-apps https://github.com/mvrpl/unix-apps &&
          brew install jq &&
          brew livecheck --tap mvrpl/unix-apps --json | jq '.[] | select(.version.outdated) | "brew bump-formula-pr \(.formula) --version=\(.version.latest) --no-fork"' | xargs -n1 bash -c '$1;exit 0' bash &&
          git branch mac-arm main && git checkout mac-arm &&
          mv $(brew --repository mvrpl/unix-apps)/*.rb . &&
          git add . && git commit -a -m "mac-arm updates" &&
          git push origin mac-arm
  livecheck-mac-intel:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Livecheck brew mac-intel
        id: brew-mac-intel
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew tap mvrpl/unix-apps https://github.com/mvrpl/unix-apps &&
          brew install jq &&
          brew livecheck --tap mvrpl/unix-apps --json | jq '.[] | select(.version.outdated) | "brew bump-formula-pr \(.formula) --version=\(.version.latest) --no-fork"' | xargs -n1 bash -c '$1;exit 0' bash &&
          git branch mac-intel main && git checkout mac-intel &&
          mv $(brew --repository mvrpl/unix-apps)/*.rb . &&
          git add . && git commit -a -m "mac-intel updates" &&
          git push origin mac-intel