name: Livechecks tap mvrpl/unix-apps

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  livecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Livecheck brew
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew tap mvrpl/unix-apps https://github.com/mvrpl/unix-apps &&
          brew install jq &&
          brew livecheck --tap mvrpl/unix-apps --json | jq '.[] | select(.version.outdated) | "\(.formula) \(.version.current) \(.version.latest)"' | xargs -n1 bash -c './update_formula.bash $@' bash &&
          cd $(brew --repository mvrpl/unix-apps) && git commit -a -m "Updates" && git push origin main