name: Livechecks tap mvrpl/unix-apps

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  brew-livecheck:
    runs-on: ubuntu-latest
    outputs:
      json-apps: ${{ steps.brew-checkver.outputs.apps }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Livecheck brew
        id: brew-checkver
        run: |
          brew tap mvrpl/unix-apps https://github.com/mvrpl/unix-apps
          brew install jq
          echo "apps=$(brew livecheck --tap mvrpl/unix-apps --json | jq -c '.')" >> "$GITHUB_OUTPUT"
  livecheck-linux:
    runs-on: ubuntu-latest
    needs: [brew-livecheck]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Livecheck brew linux
        id: brew-linux
        env:
          APPS: ${{needs.brew-livecheck.outputs.json-apps}}
        run: |
          sudo apt install -y pcregrep
          brew install jq
          update_version () { formula=$1;version=$2;sed -i 's/(v?)[0-9]+\.[0-9]+(\.[0-9]+)?/\1'$version'/g' ./${formula}.rb; }
          export -f update_version
          update_hashs () { formula=$1; paste -d ' ' <(pcregrep -o1 'url.*"(.*)"' ./${formula}.rb) <(pcregrep -o1 'sha256.*"(.*)"' ./${formula}.rb) | xargs -l bash -c 'hash=$(curl -sL $1 | sha256sum | cut -d " " -f 1);sed -i "s/$2/$hash/g" ./${formula}.rb' bash; }
          export -f update_hashs
          echo "$APPS" | jq '.[] | select(.version.outdated) | "update_version \(.formula) \(.version.latest) ; update_hashs \(.formula)"' | xargs -n1 bash -c '$1' bash
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '*.rb'
          branch: main